const fs = require('fs');
const path = require('path');
const src = path.join(__dirname, 'JobDescription.js');
const dst = path.join(__dirname, 'JobDetailsChat.js');
let c = fs.readFileSync(src, 'utf8');
c = c.replace('JobDescriptionScreen', 'JobDetailsChatScreen');
c = c.replace("const { job } = route.params || {};", "const { jobId } = route.params || {};\n  const [job, setJob] = useState(null);\n  const [loading, setLoading] = useState(true);\n  const [error, setError] = useState(null);");
c = c.replace("const { userData, refreshUserData, userProfile } = useAuth();", "const { theme, themeStyles } = useTheme();");
c = c.replace("const [isCheckingBalance, setIsCheckingBalance] = useState(false);", "");
c = c.replace(/const handleGoBack[\s\S]*?};/, "");
c = c.replace(/const handleApply[\s\S]*?};/, "");
c = c.replace(/useEffect\(\(\) => \{[\s\S]*?\}, \[job\]\);/, "useEffect(() => { fetchJobDetails(); }, [jobId]);\n\n  const fetchJobDetails = async () => {\n    try {\n      setLoading(true);\n      setError(null);\n      const apiJob = await apiService.getJobById(jobId);\n      setJob(apiJob);\n    } catch (err) {\n      setError('Unable to load job details.');\n    } finally {\n      setLoading(false);\n    }\n  };");
c = c.replace(/const checkBookmarkStatus[\s\S]*?};/, "");
c = c.replace(/const toggleFlag[\s\S]*?};/, "");
c = c.replace(/if \(!job\) \{[\s\S]*?return \([\s\S]*?\);\n  \}/, "if (loading) { return (<SafeAreaView style={{flex:1,justifyContent:'center',alignItems:'center'}}><SafeSpinner size={42} color=\"#6B21A8\" /></SafeAreaView>); }\n  if (error || !job) { return (<SafeAreaView style={{flex:1,justifyContent:'center',alignItems:'center'}}><Text>{error || 'Job not found'}</Text><TouchableOpacity onPress={() => navigation.goBack()} style={{padding:10,backgroundColor:'#6B21A8',borderRadius:8,marginTop:10}}><Text style={{color:'white'}}>Go Back</Text></TouchableOpacity></SafeAreaView>); }");
c = c.replace("const canApply = job.client?.user?.id !== userData?.id;", "");
c = c.replace(/const isRemote =[\s\S]*?!job\.latitude\);/, "const isRemote = job.location?.toLowerCase() === 'remote' || !job.location;");
c = c.replace("const isPlatformPayment = job.paymentMethod === \"PLATFORM\";", "const isPlatformPayment = job.budgetType === 'PLATFORM';");
c = c.replace(/const clientName =[\s\S]*?\"Mayur Agarwal\";/, "const clientName = job.client?.user?.fullName || job.client?.companyName || 'Client';");
c = c.replace(/const companyName = job\.client\?\.companyName[\s\S]*?\"Simplium Technologies\";/, "const companyName = job.client?.address || job.client?.city || '';");
c = c.replace(/const jobDescriptionText =[\s\S]*?\"8tc8ctc c 4d4x84c4\";/, "const jobDescriptionText = job.jobDescription || job.description || 'No description provided';");
c = c.replace(/const rawCategory = job\.jobCategory[\s\S]*?\"Graphic Designer\";/, "const rawCategory = job.jobCategory || job.category || 'General';");
c = c.replace(/const subCategoryText =[\s\S]*?\"Design & Creative\";/, "const subCategoryText = job.subcategory || job.jobSubCategory || 'Design & Creative';");
c = c.replace(/const locationText = job\.location[\s\S]*?\"123, MG Road, Connaught Place, New Delhi - 110001\";/, "const locationText = job.location || 'Remote';");
c = c.replace("const statusText = (job.jobStatus || job.status || \"OPEN\").toUpperCase();", "const statusText = (job.jobStatus || job.status || 'OPEN').toUpperCase();");
c = c.replace("onPress={handleGoBack}", "() => navigation.goBack()");
c = c.replace("onPress={handleApply}", "() => {}");
c = c.replace("disabled={!canApply || isCheckingBalance}", "disabled={false}");
c = c.replace("opacity: canApply && !isCheckingBalance ? 1 : 0.6", "opacity: 1");
c = c.replace(/\{isCheckingBalance \? \([\s\S]*?\) : \([\s\S]*?\)\}/, "<><Ionicons name=\"chatbubble-ellipses\" size={18} color=\"#FFFFFF\" style={{ marginRight: 8 }} /><Text style={styles.primaryApplyButtonText}>View Job</Text></>");
c = c.replace("Apply for Job", "View Job");
c = c.replace("handleReportJob", "() => navigation.goBack()");
c = c.replace("Report this Job", "Back to Jobs");
fs.writeFileSync(dst, c, 'utf8');
console.log('Done!');
